/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.aquapackrobotics.sw8s;

import java.util.concurrent.ScheduledThreadPoolExecutor;

import org.aquapackrobotics.sw8s.missions.*;

import java.util.concurrent.*;

public class App {

    static final int POOLSIZE = 1;
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        ScheduledThreadPoolExecutor pool = new ScheduledThreadPoolExecutor(POOLSIZE);
        String helpFlag[] = {"\nBasic Utility:", "\n'test' -- The Command Flag used in Testing", "'help' or 'h' -- displays list of command flags", "\nStates:", "\n"};
        System.out.println("Basic Format: gradle run --args='_'");        
        for (String str: args) {
            switch (str) {
                case "--test":
                    System.out.println("Yay! it worked!");
                    break;
                case "-h":
                    for(int i = 0; i < helpFlag.length; i++){
                        System.out.println(helpFlag[i]);
                    }
                case "--help":
                    for(int i = 0; i < helpFlag.length; i++){
                        System.out.println(helpFlag[i]);
                    }
                    break;
                case "--raw_test":
                    Mission missionRaw_Test = (Mission) new Raw_Test(pool);
                    missionRaw_Test.run();
                    break;
                case "--local_test":
                    Mission missionLocal_Test = (Mission) new Local_Test(pool);
                    missionLocal_Test.run();
                    break;
                case "--manual":
                    Mission missionManual = (Mission) new ManualMission(pool, 5000);
                    missionManual.run();
                    break;
                case "--motor_test":
                    Mission motorMission = (Mission) new MotorTest(pool);
                    motorMission.run();
                    break;
                case "--submerge_test":
                    Mission submergeMission = (Mission) new SubmergeTest(pool);
                    submergeMission.run();
                    break;
                default:
                    Mission missionAuto = (Mission) new AutoMission(pool);
                    missionAuto.run();
                    break;

            }
        }
    }
}
