/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.aquapackrobotics.sw8s;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        //Server classUnderTest = new Server();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
